version: '3'

services:
  my-milvus:
    image: milvusdb/milvus:v2.4.13-hotfix
    container_name: my-milvus
    environment:
      TZ: Asia/Shanghai
      ETCD_USE_EMBED: true
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      ETCD_CONFIG_PATH: /milvus/configs/embedEtcd.yaml
      COMMON_STORAGETYPE: local
    ports:
      - "19530:19530"
      - "9091:9091"
      #- "2379:2379"
    networks:
      - my-network
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml
    command: [ "milvus", "run", "standalone" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

networks:
  my-network:
    external: true
